### PR TITLE
Fix incorrect phpdoc type hints

### LINKED ISSUE #11: Bad PhpDocs
Stuff like this makes it very hard to navigate the code base when debugging...

bad-phpdocs-2

My IDE thinks $data is a string because the project says so.

bad-phpdocs

My IDE doesn't recognize the namespaces (first slash is missing, so it's relative), $data is declared a string, throws is not right.

I use PhpStorm.

Thank you for your consideration.

### PR DESCRIPTION
**Pull request by shadowhand**
Fixes #11

### CODE REVIEW

File: src/Provider/Github.php [hunk 1]
```diff
@@ -82,7 +82,7 @@ protected function getDefaultScopes()
      * @link   https://developer.github.com/v3/oauth/#common-errors-for-the-access-token-request
      * @throws IdentityProviderException
```
Comment (dac514) [inline src/Provider/Github.php:83]: Should be: `* @throws  Exception\IdentityProviderException`

**Comment by dac514** [comment]
In `src\Provider\GithubResourceOwner.php` and `src/Provider/Github.php` my IDE doesn't know what `ResourceOwner` is.

Should be `\League\OAuth2\Client\Provider\ResourceOwnerInterface` or `\League\OAuth2\Client\Provider\GithubResourceOwner`

**Comment by dac514** [comment]
(PS: Thanks for this)
